# Generated by Django 5.0.3 on 2024-03-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_ingredient_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(choices=[('gram', 'Gram'), ('kilogram', 'Kilogram'), ('milliliter', 'Milliliter'), ('liter', 'Liter')], max_length=50),
        ),
    ]
