# Generated by Django 5.0.3 on 2024-03-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Prepared', 'Prepared'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
