# Generated by Django 5.0.3 on 2024-03-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_menu_description_alter_menu_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ManyToManyField(to='restaurant.menu'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='OrderedMenuItem',
        ),
    ]
