# Generated by Django 5.0.3 on 2024-03-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_remove_foodpreparation_order_remove_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
