# Generated by Django 5.0.3 on 2024-03-29 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_cart_fooditem_cartitem_ingredientquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu'),
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
