# Generated by Django 5.0.3 on 2024-03-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_alter_ingredientquantity_food_item_delete_fooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit_of_measurement',
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='unit_of_measurement',
            field=models.CharField(choices=[('gram', 'Gram'), ('kilogram', 'Kilogram'), ('milliliter', 'Milliliter'), ('liter', 'Liter')], default='gram', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit_of_measurement',
            field=models.CharField(choices=[('gram', 'Gram'), ('kilogram', 'Kilogram'), ('milliliter', 'Milliliter'), ('liter', 'Liter')], default='gram', max_length=50),
        ),
    ]
