# Generated by Django 5.0.3 on 2024-03-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_remove_ingredient_price_remove_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(choices=[('gram', 'Gram'), ('kilogram', 'Kilogram'), ('milliliter', 'Milliliter'), ('liter', 'Liter')], default='gram', max_length=50),
        ),
    ]
