# Generated by Django 5.0.3 on 2024-03-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_remove_menu_list_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='food_item',
            new_name='menu_item',
        ),
    ]
