# Generated by Django 5.0.3 on 2024-03-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_rename_food_item_ingredientquantity_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='menu',
            name='ingredient',
            field=models.CharField(default='onion', max_length=250),
        ),
    ]
