# Generated by Django 5.0.3 on 2024-03-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_remove_cartitem_cart_remove_cartitem_menu_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
