# Generated by Django 5.0.3 on 2024-03-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_delete_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('visa', 'Visa'), ('telebirr', 'Telebirr'), ('mobilebank', 'Mobile_Bank')], max_length=50),
        ),
    ]
