# Generated by Django 5.0.3 on 2024-03-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='menu',
            name='ingredients',
            field=models.ManyToManyField(to='restaurant.ingredient'),
        ),
    ]
